# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default

steps:

- script: |
    npm install
    displayName: 'npm install '

- task: FortifySCA@7
  inputs:
    applicationType: 'other'
    buildAnalyzerParams: '-exclude ./node_modules/*'
    fortifyBuildId: 'nodejs-project-backend'
    scaVerbose: true
    scaDebug: true
    fortifyScanType: 'LocalScan'
    runFortifyUpload: true
    fortifyApplicationIdentifierType: 'byId'
    fortifyApplicationVersionId: '10028'
